# 游戏包名配置文件（每行1个包名，#开头为注释）
# 进入下列游戏前台时，本模块会自动停止 horae 进程；退出游戏后恢复。

# 示例游戏包名（根据自己的游戏修改）
com.tencent.tmgp.pubgmhd  # 和平精英
com.netease.dwrg          # 荒野行动
com.tencent.ig            # 使命召唤手游
com.tencent.tmgp.sgame
